// Generated by https://quicktype.io

export interface LoginData {
    correo:   string;
    password: string
}

export interface RegisterData {
    correo:   string;
    password: string;
    nombre:   string;
    nif: string
}

export interface LoginResponse {
    usuario: Usuario;
    token:   string;
}

export interface Usuario {
    rol:    string;
    estado: boolean;
    google: boolean;
    nombre: string;
    correo: string;
    uid:    string;
    img?:   string;
}
// Generated by https://quicktype.io

export interface NegociosResponse {
    total:     number;
    negocios: Negocio[];
}

export interface Negocio {
    precio:    number;
    _id:       string;
    nombre:    string;
    categoria: Categoria;
    usuario:   Categoria;
    img?:      string;
}

// export interface Categoria {
//     _id:    string;
//     nombre: string;
// }

// Generated by https://quicktype.io

export interface CategoriesResponse {
    total:      number;
    categorias: Categoria[];
}

export interface Categoria {
    _id:     string;
    nombre:  string;
    usuario?: CreadoPor;
}

export interface CreadoPor {
    _id:    string;
    nombre: string;
}


// Generated by https://quicktype.io

export interface Negocio {
    _id:         string;
    nombre:      string;
    categoria:   Categoria;
    img?:         string;
    direccion?:   string;
    longitude?:   string;
    latitude?:    string;
    descripcion?: string;
    usuario:     Categoria;
}

export interface Creador {
    _id:    string;
    nombre: string;
}

// Generated by https://quicktype.io

export interface Oferta {
    precio:      number;
    _id:         string;
    nombre:      string;
    img:         string;
    negocio:     string;
    descripcion: string;
    usuario:     UsuarioBasico;
}

export interface UsuarioBasico {
    _id:    string;
    nombre: string;
}



